FROM python:3.8-slim-buster
WORKDIR /app
COPY requirements.txt requirements.txt
RUN mkdir /root/.kube
RUN pip install -r requirements.txt
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x kubectl && mv ./kubectl /usr/bin/kubectl
COPY . .
ENTRYPOINT [ "./start.sh" ]