FROM python:3.8-slim-buster
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git curl nano
COPY . .
RUN groupadd -r demo && useradd -r -g demo demo && mkdir /home/demo && chown demo:demo /home/demo 
USER demo
CMD [ "python3", "-u", "Main.py" ]